Ruby group capstone - Catalog of my things
brighton0102/Catalog-of-my-things pull request #16
Opened 2024-01-13 15:20 UTC by brighton0102

### In this milestone I : 

[ ] Each class from the [UML class diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png) should be created in a separate .rb file.
[ ] All associations (1-to-many relationships) and aggregations (parent-child relationships) between classes should be implemented.
[ ] All properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
[ ] All methods visible in the diagram should be implemented:

1. add_item method (in all classes that have that method)
2. should take an instance of the Item class as an input.
3. should add the input item to the collection of items.
4. should add self as a property of the item object (by using the correct setter from the item object).

- [ ] can_be_archived?() in the Item class

1. should return true if published_date is older than 10 years.
2. otherwise, it should return false.

- [ ] move_to_archive() in the Item class

1.  should reuse can_be_archived?() method.
2.  should change the archived property to true if the result of the can_be_archived?() method is true.
3.  should do nothing if the result of the can_be_archived?() method is false.

- [ ] can_be_archived?() in the Book class

1. [ ] should override the method from the parent class.
2. [ ] should return true if parent's method returns true OR if cover_state equals to "bad".
3. [ ] otherwise, it should return false.

- [ ] can_be_archived?() in the MusicAlbum class

1. should override the method from the parent class.
2. should return true if parent's method returns true AND if on_spotify equals true.
3. otherwise, it should return false.

- [ ] can_be_archived?() in the Movie class

1. should override the method from the parent class.
2. should return true if parent's method returns true OR if silent equals true.
3. otherwise, it should return false.

- [ ] can_be_archived?() in the Game class

1. should override the method from the parent class.
2. should return true if parent's method returns true AND if last_played_at is older than 2 years.
3. otherwise, it should return false.

- [ ] Add unit tests for all implemented methods.

![image](https://github.com/brighton0102/Catalog-of-my-things/assets/103440988/cc9ba1af-3d31-460d-9a25-4c96ce202df4)

2024-01-13 18:47 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @brighton0102 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/4xsT7Fa4IxbMCNroH3/giphy.gif"/>

## Highlights :fire: 
- Linters well setup and passing :heavy_check_mark: 
- Presentation video included and well presented :heavy_check_mark: 
- Most project requirements implemented :heavy_check_mark: 
- All written tests passing :heavy_check_mark: 
- SQL tables present in the project :heavy_check_mark: 
- Console app works almost completely :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers ,and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-13 18:47 UTC, nahnahdev commented on classes/genre.rb
> +  end
- [ ] Great job so far @brighton0102 There are just a few changes I will suggest you implement and you'll be on your way to the next Milestone :wink: 
- [ ] I noticed here that your relationship between `Genre` and `Items` is not defined both ways. To fix this you need to adapt your solution to manage both sides of the relationship in both cases. You need to modify your implementations of `add_item` in `Genre` and create a setter for `@genre` in `Item`.
- Example
```ruby
    def add_item(item)
      @items.push(item)
      item.genre = self
    end
```

2024-01-13 18:47 UTC, nahnahdev commented on classes/author.rb
> +  end
- [ ] Just as I mentioned in [this comment](https://github.com/brighton0102/Catalog-of-my-things/pull/16#discussion_r1451576533), I will suggest you implement similar changes here as well :+1: 
- [ ] The relationship between `Author` and `Items` is not defined both ways. To fix this you need to adapt your solution to manage both sides of the relationship in both cases. You need to modify your implementations of `add_item` in `Author` and create a setter for `@author` in `Item`.
- Example
```ruby
    def add_item(item)
      @items.push(item)
      item.author = self
    end
```

2024-01-13 18:47 UTC, nahnahdev commented on classes/label.rb
> +  end
- [ ] A similar change also needs to be implemented here. You can see that your relationship between `Label` and `Items` is not defined both ways. To fix this you need to adapt your solution to manage both sides of the relationship in both cases. You need to modify your implementations of `add_item` in `Label` and create a setter for `@label` in `Item`.
- Example
```ruby
    def add_item(item)
      @items.push(item)
      item.label = self
    end
```

2024-01-13 18:47 UTC, NahnahAJ commented on classes/item.rb
> +  attr_reader :id, :archived
- [ ] Kindly ensure that your `Item Class` includes `attr_reader` for these attributes. :wink: 

```ruby
  attr_reader :genre
  attr_reader :author
  attr_reader :label
```

2024-01-13 18:47 UTC, NahnahAJ commented on main.rb
> +  puts '6. List all authors'
- [ ] Great job @brighton0102 Almost all your console commands work as expected. I only encountered an error when I tried to view all `Authors` by accessing option `6` but this threw an error and shut down the app. So kindly make those changes so your app can display all authors and work as expected :wink: 
- [ ] Error Message
![image](https://github.com/brighton0102/Catalog-of-my-things/assets/102699958/5e3af85f-1ada-476a-ad3a-2efff61abe21)

2024-01-13 18:47 UTC, NahnahAJ commented on operations/file_operations.rb
> +    class_mapping[class_name].from_json(item_data)
- [ ] I also noticed that once `Quit` the console app and I tried to restart the app to check if Data was preserved and to also check whether your method to get back all the data that was created indeed works as expected, the app didn't start at all. So kindly fix that as well :+1: I have attached the error message below.
- [ ] So kindly ensure that Data is well Preserved in your console app and stored data from the `.json files` is loaded when the app starts. Kindly ensure that your app also starts without any errors :wink: 
- Error Message
![image](https://github.com/brighton0102/Catalog-of-my-things/assets/102699958/ba97b9a2-7222-4442-a776-24b2a4b5a4a8)

2024-01-13 20:41 UTC, Gambit142 requested changes
Hi @brighton0102 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- Created classes ✔️ 
- Created SQL tables using schema diagram ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-13 20:41 UTC, Gambit142 commented on main.rb
> +end
- [ ] Great work making most of the required changes, however, I noticed that when I try to _**Add a book**_ or try to _**Add a game**_, I get errors in the console application that you created. Kindly fix these errors. 👍 😎 

#### Error When trying to add a book

![image](https://github.com/brighton0102/Catalog-of-my-things/assets/77106962/4efd248b-b0b1-4073-8b53-af38f88fc72a)

#### Error when trying to add a game

![image](https://github.com/brighton0102/Catalog-of-my-things/assets/77106962/2e1ec206-16da-41af-a225-9716d4db8d0f)

#### N.B: Please ensure that all options of the console application work properly after fixing the errors and that a user can save data to JSON files and load data fro the JSON files upon reentry. 💻 🖱️

2024-01-14 00:32 UTC, Reem-lab approved these changes
# Hi Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Descriptive PR⭐
- [ ]  No Linters error 🤩
- [ ] Good job working on the saving data into JSONs💪🏻
- [ ] Amazing job working on the main file 🔥🔥
- [ ] Great for making the requested changes ⭐
- [ ] All options working fine 🔥

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-16 08:42 UTC, merged